project:
  type: website

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

  resources:
    - "files/**"
    - "etc/**"

website:
  title: "Me"
  description: "Personal website of Edoardo Filippi"
  site-url: https://edo98811.github.io/ 

  navbar:
    left:
      - text: "Blog"
        href: blog/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "CV"
        href: CV/index.qmd
    right:
      - icon: github
        href: https://github.com/edo98811
  page-footer: 
      left: |
        Edoardo Filippi - 2024
      center: |
      right: |
        Built with [Quarto](https://quarto.org)


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
